### ISSUE TITLE
docker-compose for Postgresql

### ISSUE THREAD

**Issue by shahwan42** [wsvincent/djangox#28]
Installing and configuring Postgres on the system is a hassle for me, I like to use a containerized version for development... and I'd like to add it to this boilerplate... is that ok?

**Comment by wsvincent** [comment]
I'm interested to see what you have in mind. I use Docker + PostgreSQL personally and I've debated adding an option for it here as well. Do share how you like to configure!

**Comment by franciscojavierarceo** [comment]
I’ve actually added the docker + Postgres setup on my branch.

I need to pull in your latest changes but I added a couple of other items as well.

**Comment by shahwan42** [comment]
Required files:

docker-compose.yml
```yml
version: '3'

volumes:
  local_postgres_data: 

services:
  postgres:
    image: postgres:11.3-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
```

.env
```sh
# PostgreSQL
# ------------------------------------------------------------------------------
POSTGRES_HOST=localhost
POSTGRES_PORT=5432
POSTGRES_DB=db-name
POSTGRES_USER=db-user
POSTGRES_PASSWORD=db-password
```
Usage:
`$ docker-compose up`  # to run Postgres
`python manage.py runserver`  # to run django

That's easier for development... My editor (VS Code, which is widely used, too) will use my local `venv` to autocomplete, and Django will use the dockerized version of Postgres without a complaint...

Also, managing other projects is fairly easier, no DB setup is needed... just up and running the docker-compose...

Running multiple databases and Django servers at the same time will require changing the ports for each... which is fairly easy this way, too...
